apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: idx4g11kn-java-springboot-gitops
  description: This is GitOps manifest for idx4g11kn-java-springboot   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=idx4g11kn-java-springboot
    backstage.io/kubernetes-id: idx4g11kn-java-springboot 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: idx4g11kn-java-springboot-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:idx4g11kn-java-springboot
